"use client";

import React, { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  bn: {
    // Navbar
    brand_title: "পূজা পরিক্রমা",
    brand_subtitle: "বর্ধমান সংস্করণ",
    how_it_works: "কীভাবে কাজ করে",
    pandal_list: "মণ্ডপ তালিকা",
    route_planner: "রুট প্ল্যানার",
    live_map: "লাইভ ম্যাপ",
    start_tour: "পরিক্রমা শুরু করুন",
    
    // HUD / Voice
    arrive: "আপনি {name}-এ পৌঁছে গেছেন। এখন ঠাকুর উপভোগ করুন!",
    turn_left: "বাঁদিকের রাস্তায় যান",
    turn_right: "ডানদিকের রাস্তায় যান",
    straight: "সোজা এগিয়ে চলুন",
    uturn: "ইউ-টার্ন নিন",
    meters_after: "মিটার পর",
    skip: "পরবর্তী মণ্ডপ",
    end: "শেষ করুন",
    tour_complete: "সফর শেষ",
    distance: "দূরত্ব",
    stop: "স্টপ",
    yes_reached: "হ্যাঁ, পৌঁছে গেছি",
    not_yet: "না, পৌঁছাইনি",
    next_pandal: "পরবর্তী মণ্ডপে চলুন ➔",
    checkin_complete: "দর্শন সম্পন্ন",
    route_builder: "রুট প্ল্যানার",
    select_pandals: "ম্যাপ থেকে মণ্ডপ বেছে নিন।",
    enable_mode: "ম্যাপ মোড খুলুন",
    exit_mode: "বন্ধ করুন",
    quick_stats: "একনজরে",
    total_pandals: "মোট মণ্ডপ",
    high_crowd: "ভিড় বেশি",
    add_to_route: "+ রুটে যোগ করুন",
    added: "✔ যোগ করা হয়েছে",
    transport_mode: "যাতায়াতের মাধ্যম",
    
    // Hero Landing
    hero_pill: "বর্ধমান • কাটোয়া • 2026",
    hero_title: "চলো, পূজো দেখতে যাই",
    hero_title_p1: "চলো,",
    hero_title_p2: "পূজো দেখতে যাই",
    hero_motto: "যেখান থেকে শুরু, সেখানেই শেষ. সেরা মণ্ডপগুলো কম সময়ে",
    hero_one_line: "সবচেয়ে কম সময়ে, কম জ্যামে, সেরা পণ্ডেলগুলো ঘুরে দেখুন। ফ্রি, লগইন ছাড়াই।",
    hero_btn_start: "পরিক্রমা শুরু করুন",
    hero_btn_hiw: "কীভাবে কাজ করে",
    hero_subline: "23টি মণ্ডপ · বর্ধমান ও কাটোয়া · বাংলায় ভয়েস গাইড",
    hero_stat_pandals: "23টি মণ্ডপ",
    hero_stat_cities: "বর্ধমান ও কাটোয়া",
    hero_stat_voice: "বাংলায় ভয়েস গাইড",
    hero_intro_text: "বর্ধমান ও কাটোয়ার সেরা দুর্গাপূজা মণ্ডপগুলো সবচেয়ে কম সময়ে ঘুরে দেখুন। আমাদের রুট প্ল্যানার স্বয়ংক্রিয়ভাবে সবচেয়ে কম দূরত্বে রুট তৈরি করে, এবং বাংলায় ভয়েস গাইড দিয়ে হাঁটার পথ দেখায়। ফ্রি, লগইন ছাড়াই।",

    // Section 2: Features
    feat_sec_title: "শুধু রুট প্ল্যানার নয়",
    feat_sec_sub: "পূজো পরিক্রমার সব টুল",
    feat1_card_t: "সেরা মণ্ডপ এক ট্যাপে",
    feat1_card_d: "Top 5, Top 10 বা Top 15 — সিস্টেম নিজেই সেরা রুট বানায়।",
    feat2_card_t: "সময় অনুযায়ী রুট",
    feat2_card_d: "2 ঘণ্টা থেকে সারা দিন — যতটা সময় আছে, ততটাই মণ্ডপ।",
    feat3_card_t: "যেকোনো মণ্ডপ খুঁজুন",
    feat3_card_d: "সার্চ করে সরাসরি Google Maps-এ navigate করুন।",
    feat4_card_t: "নিজের রুট বানান",
    feat4_card_d: "ম্যাপ থেকে পছন্দের মণ্ডপ বাছুন, সিস্টেম রুট সাজিয়ে দেবে।",
    feat5_card_t: "বন্ধুদের সাথে শেয়ার",
    feat5_card_d: "রুট বানিয়ে লিংক শেয়ার করুন, বন্ধুরাও একই রুট পাবে।",
    feat6_card_t: "বাংলায় ভয়েস গাইড",
    feat6_card_d: "মোড়ে মোড়ে বাংলায় নির্দেশনা, ফোনে তাকাতে হবে না।",

    // Section 3: How it works
    hiw_sec_title: "কীভাবে ব্যবহার করবেন?",
    hiw_sec_sub: "মাত্র 4টি সহজ ধাপে শুরু করুন",
    hiw1_n: "01",
    hiw1_t: "লোকেশন চালু করুন",
    hiw1_d: "ব্রাউজার আপনার অবস্থান শনাক্ত করবে।",
    hiw2_n: "02",
    hiw2_t: "সময় বেছে নিন",
    hiw2_d: "2/4/6 ঘণ্টা বেছে নিন, বা Top 5 / Top 10 ট্যাপ করুন।",
    hiw3_n: "03",
    hiw3_t: "পরিক্রমা শুরু করুন",
    hiw3_d: "এক ট্যাপে রুট তৈরি হবে, তারপর হাঁটতে শুরু করুন।",
    hiw4_n: "04",
    hiw4_t: "রুট অনুসরণ করুন",
    hiw4_d: "নীল রুট ও বাংলা ভয়েস গাইড অনুসরণ করুন।",
    hiw_cta_btn: "এখনই শুরু করুন",

    // Section 3.5: Why Cholo Pujo
    why_sec_title: "কেন চলো পুজো?",
    why_sec_sub: "পুজো পরিক্রমা এবার আরও সহজ, আরও আনন্দময়",
    why1_t: "সময় বাঁচান",
    why1_d: "কম জ্যামে, বেশি পণ্ডেল দেখুন।",
    why2_t: "সবার জন্য ফ্রি",
    why2_d: "কোনো লগইন নেই, কোনো বিজ্ঞাপন নেই।",
    why3_t: "যেকোনো ফোনে",
    why3_d: "অ্যাপ ডাউনলোড করার দরকার নেই।",
    why4_t: "নিজের শহর, নিজের পুজো",
    why4_d: "বর্ধমান ও কাটোয়া থেকে শুরু, আরও শহর আসছে।",

    // Section 4: Cities covered
    city_sec_title: "যেসব শহরে আছে",
    city_sec_sub: "আরও শহর যোগ হচ্ছে শীঘ্রই",
    city1_name: "বর্ধমান",
    city1_count: "17টি মণ্ডপ",
    city1_status: "উপলব্ধ",
    city2_name: "কাটোয়া",
    city2_count: "6টি মণ্ডপ",
    city2_status: "উপলব্ধ",
    city3_name: "কলকাতা",
    city3_count: "শীঘ্রই আসছে",
    city3_status: "coming soon",

    // Section 5: Local businesses
    biz_sec_title: "স্থানীয় ব্যবসা",
    biz_sec_sub: "কাছের দোকান ও খাবারের জায়গা",
    biz_sponsored: "(স্পনসর্ড)",
    biz_empty: "আপনার ব্যবসা এখানে দেখাতে চান? যোগাযোগ করুন: +91 62951 11477, +91 99079 62182",
    biz_show_more: "আরও দেখান",
    biz_show_less: "কম দেখান",
    biz_loading: "লোড হচ্ছে...",

    // Section 6: Support project
    supp_sec_title: "সমর্থন জানান",
    supp_sec_sub: "এই প্রজেক্টটি সম্পূর্ণ ফ্রি",
    supp_body: "আমরা কোনো বিজ্ঞাপন বা সাবস্ক্রিপশন নেই। যদি এই উদ্যোগ আপনার পূজো পরিক্রমায় সাহায্য করে, আপনি চাইলে সামান্য অবদান রাখতে পারেন, যা পরের বছরের সার্ভার খরচ এবং আরও শহরে ছড়িয়ে দিতে কাজে লাগবে।",
    supp_qr_scan: "UPI দিয়ে স্ক্যান করুন",
    supp_qr_note: "যেকোনো পরিমাণ, ₹10, ₹50, ₹100",
    supp_qr_soon: "QR কোড শীঘ্রই আসছে",
    supp_amt_label: "পরিমাণ বাছুন",
    supp_custom_amt: "নিজের ইচ্ছেমতো পরিমাণ",
    supp_amt_placeholder: "পরিমাণ লিখুন",
    supp_pay_button: "UPI দিয়ে ₹{amt} পাঠান",
    supp_scan_pay: "₹{amt} পাঠাতে স্ক্যান করুন",
    supp_upi_note: "Google Pay, PhonePe, Paytm সহ সব UPI অ্যাপে কাজ করে",

    // Section 7: Emergency numbers
    emerg_sec_title: "জরুরি নম্বর",
    emerg_sec_sub: "পূজোর সময় প্রয়োজন হলে",
    emerg1_name: "পুলিশ কন্ট্রোল",
    emerg1_num: "100",
    emerg2_name: "হাসপাতাল",
    emerg2_num: "108",
    emerg3_name: "অ্যাম্বুলেন্স",
    emerg3_num: "102",
    emerg4_name: "দমকল",
    emerg4_num: "101",

    // Section 8: Footer
    foot_tagline: "কম সময়ে, অটোমেটিক রুট",
    foot_init: "একটি উদ্যোগ",
    foot_nav_title: "ন্যাভিগেশন",
    foot_home: "হোম",
    foot_start: "পরিক্রমা শুরু করুন",
    foot_hiw: "কীভাবে কাজ করে",
    foot_list: "পণ্ডেল তালিকা",
    foot_cities_title: "শহরসমূহ",
    foot_bwn: "বর্ধমান",
    foot_ktw: "কাটোয়া",
    foot_more: "আরও শহর (শীঘ্রই)",
    foot_contact_title: "যোগাযোগ",
    foot_whatsapp: "হোয়াটসঅ্যাপে যোগাযোগ",
    foot_email: "যোগাযোগ: contact@devsaha.tech",
    foot_feedback: "মতামত জানান",
    foot_github: "GitHub",
    foot_copy: "© 2026 DevSaha Tech · সব অধিকার সংরক্ষিত",
    foot_terms: "এই সাইটটি ব্যবহার করে আপনি আমাদের শর্তাবলী মেনে নিচ্ছেন।",
    stat_verified: "ভেরিফায়েড মণ্ডপ",
    stat_lag: "সার্ভার ল্যাগ",
    stat_free: "সম্পূর্ণ ফ্রি",
    stat_lang: "বাংলায়",
    stat_turn: "টার্ন গাইডেন্স",
    
    // Features
    feat_title: "আমরা কী কী দিচ্ছি",
    feat_desc: "উৎসবে যোগ দিন কোনো বাধা ছাড়াই। আমাদের এই ফিচারগুলো আপনার পরিক্রমাকে করবে আরও সহজ।",
    feat1_t: "শর্টেস্ট রাউন্ড-ট্রিপ (2-Opt TSP)",
    feat1_d: "যেখান থেকে পুজো দেখতে বেরোবেন, সমস্ত ঠাকুর দেখে সবচেয়ে কম সময়ে সেখানেই ফিরে আসবেন।",
    feat2_t: "টাইম বাজেট প্ল্যানার",
    feat2_d: "আপনার হাতে ঠিক কত ঘণ্টা সময় আছে সিলেক্ট করুন; সিস্টেম নিজে থেকে সেরা মণ্ডপগুলো বেছে রুট সাজিয়ে দেবে।",
    feat3_t: "বাংলায় ভয়েস নেভিগেশন",
    feat3_d: "রাস্তায় হাঁটার সময় ফোনে বারবার তাকাতে হবে না, মোড়ে মোড়ে বাংলায় অডিও গাইডেন্স জানিয়ে দেবে কোন দিকে যাবেন।",
    feat4_t: "পুলিশ নো-এন্ট্রি ও ট্রাফিক ফিল্টার",
    feat4_d: "বর্ধমান ট্রাফিক পুলিশের সাময়িক ব্যারিকেড ও ওয়ান-ওয়ে এড়িয়ে শুধু হাঁটার নিরাপদ রুট।",
    culture_title: "বর্ধমানের ঐতিহ্য ও সংস্কৃতি",
    culture_desc1: "শতাব্দী প্রাচীন সর্বমঙ্গলা বাড়ী, ঐতিহাসিক কার্জন গেট, 108 শিব মন্দির, আর বাদামতলা ও আলমগঞ্জের বর্ণাঢ্য বারোয়ারী দুর্গাপূজার অপরূপ সৌন্দর্য, সব মিলিয়ে আমাদের এই পরিক্রমা।",
    culture_desc2: "মা দুর্গার আগমনে সেজে উঠুক আমাদের এই প্রাচীন শহর।",
    

    // Footer
    foot_greeting: "শুভ শারদীয়ার প্রীতি, শুভেচ্ছা ও আন্তরিক অভিনন্দন।",
    foot_desc: "বর্ধমানের উৎসবপ্রেমী মানুষদের জন্য তৈরি একটি সম্পূর্ণ ফ্রি ও ওপেন সোর্স প্রজেক্ট। আসুন সবাই মিলে এক সুন্দর, সুশৃঙ্খল ও জ্যামমুক্ত পুজো উপভোগ করি।",
    foot_emergency: "জরুরি হেল্পলাইন",
    foot_police: "বর্ধমান পুলিশ কন্ট্রোল",
    foot_hospital: "বর্ধমান মেডিকেল কলেজ হাসপাতাল",
    
    // Feedback
    feedback_button_aria: "মতামত জানান",
    feedback_title: "আপনার মতামত জানান",
    feedback_category_label: "বিভাগ",
    feedback_category_general: "সাধারণ মতামত",
    feedback_category_bug: "সমস্যা / বাগ",
    feedback_category_suggestion: "পরিবর্তনের প্রস্তাব",
    feedback_category_add_pandal: "নতুন মণ্ডপ যোগ করুন",
    feedback_category_data: "তথ্য সংশোধন",
    feedback_category_other: "অন্যান্য",
    feedback_pandal_name_label: "মণ্ডপের নাম",
    feedback_message_label: "আপনার মতামত",
    feedback_message_placeholder: "এখানে লিখুন...",
    feedback_submit: "পাঠান",
    feedback_cancel: "বাতিল",
    feedback_thanks: "ধন্যবাদ! আপনার মতামত আমরা পেয়েছি।",
    feedback_error: "দুঃখিত, পাঠানো যায়নি। আবার চেষ্টা করুন।",
    
    // Planner Phase 9B
    pl_time_label: "কত সময় আছে?",
    pl_time_2h: "2 ঘণ্টা",
    pl_time_4h: "4 ঘণ্টা",
    pl_time_6h: "6 ঘণ্টা",
    pl_time_allday: "সারা দিন",
    pl_time_other: "সময় লিখুন (মিনিট)",
    pl_other_time_title: "সময় লিখুন (মিনিট)",
    pl_other_time_placeholder: "৩০ থেকে ৭২০ এর মধ্যে লিখুন",
    pl_other_time_confirm: "ঠিক আছে",
    pl_other_time_cancel: "বাতিল",
    pl_other_time_error_title: "ভুল সময়",
    pl_other_time_error_body: "৩০ থেকে ৭২০ মিনিটের মধ্যে একটি সংখ্যা লিখুন।",
    pl_more_options: "আরও বিকল্প",
    pl_start_tour: "পরিক্রমা শুরু করুন",
    pl_open_gmaps: "Google Maps-এ খুলুন",
    pl_share: "শেয়ার",
    pl_select_from_map: "ম্যাপ থেকে বাছুন",
    pl_selected_count: "{n}টি মণ্ডপ বেছেছেন",
    pl_confirm: "সম্পূর্ণ করুন",
    pl_cancel: "বাতিল",
    pl_open_first_10: "প্রথম 10টি দিয়ে শুরু করুন",
    pl_one_by_one: "একটা একটা করে যান",
    pl_more_than_10: "10টির বেশি মণ্ডপ Google Maps-এ একসাথে দেখানো যাবে না।",
    pl_continue_batch: "প্রথম 10টি শেষ? পরের {n}টির জন্য ক্লিক করুন",
    share_title: "আমার পূজো পরিক্রমার রুট",
    share_text: "চলো পূজো দেখতে যাই! {n}টি মণ্ডপ",
    share_copied: "লিংক কপি হয়েছে",
    search_pandals: "মণ্ডপ খুঁজুন...",
    batch_progress: "ব্যাচ {n} / {total}",
    batch_continue: "পরেরটির জন্য ক্লিক করুন",
    batch_done_toast: "সব মণ্ডপ দেখা শেষ!",
    site_visitors: "মোট ওয়েবসাইট দর্শনার্থী",

    pl_map_loading: "ম্যাপ লোড হচ্ছে...",
    pl_top_n_all: "সব",
    pl_load_error: "লোড করতে সমস্যা হয়েছে, আবার চেষ্টা করুন।",
    pl_start_location: "শুরুর স্থান",
    pl_other_time_title: "কত মিনিট সময় আছে?",
    pl_other_time_placeholder: "30 থেকে 720 মিনিট",
    pl_other_time_confirm: "ঠিক আছে",
    pl_other_time_cancel: "বাতিল",
    pl_all_pandals_visited: "সব মণ্ডপ দেখা শেষ!",
    pl_hope_enjoyed: "আশা করি ভালো লেগেছে।",
    pl_from_your_location: "আপনার অবস্থান থেকে",
    pl_tap_to_view_list: "তালিকা দেখতে ট্যাপ করুন",
    pl_clear_all: "সব মুছুন",
    pl_batch_first_done: "প্রথম {n}টি শেষ? পরেরটির জন্য ক্লিক করুন",
    pl_batch_almost: "প্রায় শেষ, বাকি {n}টি মণ্ডপ",
    pl_batch_counter: "ব্যাচ {current} / {total}",
    pl_time_pick_hint: "সময় বেছে নিন, আমরা সেরা রুট বানিয়ে দেব",
    pl_device_error_title: "অসমর্থিত ডিভাইস",
    pl_device_error_text: "আপনার ডিভাইসে লোকেশন সার্ভিস সাপোর্ট করছে না।",
    map_no_location: "আপনার লাইভ লোকেশন পাওয়া যাচ্ছে না। দয়া করে GPS অন করুন।",
    map_too_far: "আপনি মণ্ডপ থেকে অনেক দূরে আছেন ({dist} মিটার)। 120 মিটারের মধ্যে এলে চেক-ইন করতে পারবেন।",
    map_already_checked_in: "আপনি ইতিমধ্যে এই মণ্ডপে চেক-ইন করেছেন! 2 ঘণ্টা পর আবার চেষ্টা করুন।",
    map_checkin_success: "চেক-ইন সফল হয়েছে!",
    map_checkin_error: "চেক-ইন করতে সমস্যা হয়েছে।",
    map_osrm_fallback: "OSRM লিমিট পৌঁছেছে, সরাসরি রুট দেখানো হচ্ছে",
    map_visitors_present: "জন দর্শনার্থী উপস্থিত",
    map_take_me_here: "এখানে যান",
    map_remove_from_route: "- তালিকা থেকে বাদ দিন",
    map_add_to_route: "+ রুটে যোগ করুন",
    map_checkin_near: "নিকটে গেলে চেক-ইন করতে পারবেন",
    map_checkin: "চেক-ইন",
    map_give_tips: "টিপস দিন",
    hud_tour_complete_voice: "আপনি শুরুর স্থানে পৌঁছে গেছেন। চলো পূজো ব্যবহার করার জন্য ধন্যবাদ!",
    hud_arrival_voice: "{name}-এ পৌঁছে গেছেন। এখন ঠাকুর উপভোগ করুন!",
    hud_tour_complete_title: "শুরুর স্থানে পৌঁছেছেন!",
    hud_tour_complete_sub: "চলো পূজো ব্যবহার করার জন্য ধন্যবাদ!",
    hud_open_gmaps: "Google Maps-এ চলুন",
    hud_generic_pandal: "মণ্ডপ",
    hud_turn_distance: "{dist} মিটার পর {instruction}",
    hud_next_pandal: "পরবর্তী মণ্ডপ {name}, আর {dist} মিটার",
    feedback_pandal_placeholder: "যেমন: সর্বমঙ্গলা",
    review_submitting: "সাবমিট হচ্ছে...",
    gps_required_title: 'জিপিএস চালু করুন',
    gps_required_body: 'এই ফিচারটি ব্যবহার করতে সাইটের লোকেশন পারমিশন দিতে হবে।',
    gps_required_ok: 'ঠিক আছে',
    gps_required_cancel: 'বাতিল',
    gps_blocked_title: 'লোকেশন ব্লক করা আছে',
    gps_blocked_body: 'আপনার ব্রাউজারে এই সাইটের লোকেশন ব্লক করা আছে। সেটিংস থেকে <b>Location → Allow</b> করে আবার চেষ্টা করুন।',
  },
  en: {
    // Navbar
    brand_title: "Puja Parikrama",
    brand_subtitle: "Bardhaman Edition",
    how_it_works: "How it Works",
    pandal_list: "Pandal List",
    route_planner: "Route Planner",
    live_map: "Live Map",
    start_tour: "Start Live Tour",
    
    // HUD / Voice
    arrive: "You have arrived at {name}. Enjoy the Puja!",
    turn_left: "Turn left",
    turn_right: "Turn right",
    straight: "Go straight",
    uturn: "Make a U-Turn",
    meters_after: "meters",
    skip: "Skip Stop",
    end: "End Tour",
    tour_complete: "Tour Complete",
    distance: "Distance",
    stop: "Stop",
    yes_reached: "Yes, Reached",
    not_yet: "Not Yet",
    next_pandal: "Next Pandal ➔",
    checkin_complete: "Check-in Complete",
    route_builder: "Route Builder",
    select_pandals: "Select pandals from the map.",
    enable_mode: "Enable Mode",
    exit_mode: "Exit Mode",
    quick_stats: "Quick Stats",
    total_pandals: "Total Pandals",
    high_crowd: "High Crowd",
    add_to_route: "+ Add to Route",
    added: "✔ Added",
    transport_mode: "Transport Mode",
    
    // Hero Landing
    hero_pill: "Bardhaman • Katwa • 2026",
    hero_title: "Let's go pandal hopping",
    hero_title_p1: "Let's go",
    hero_title_p2: "pandal hopping",
    hero_motto: "Start from where you are, end at the same place. The best pandals in less time",
    hero_one_line: "Visit the best pandals in the shortest time with minimal traffic. Free, no login required.",
    hero_btn_start: "Start Pandal Hopping",
    hero_btn_hiw: "How it works",
    hero_subline: "23 Pandals · Bardhaman & Katwa · Voice Guide in Bengali",
    hero_stat_pandals: "23 Pandals",
    hero_stat_cities: "Bardhaman & Katwa",
    hero_stat_voice: "Voice Guide in Bengali",
    hero_intro_text: "Visit the best Durga Puja pandals in Bardhaman and Katwa in the least time. Our route planner builds the shortest path automatically and guides you with Bengali voice navigation. Free, no login.",

    // Section 2: Features
    feat_sec_title: "More Than a Route Planner",
    feat_sec_sub: "Tools for every Puja parikrama",
    feat1_card_t: "Top Pandals, One Tap",
    feat1_card_d: "Top 5, Top 10, or Top 15 — auto-routed for you.",
    feat2_card_t: "Time-Based Routing",
    feat2_card_d: "From 2 hours to all day, we fit as many pandals as possible.",
    feat3_card_t: "Find Any Pandal",
    feat3_card_d: "Search and navigate directly in Google Maps.",
    feat4_card_t: "Build Your Own Route",
    feat4_card_d: "Pick pandals from the map, we sort the best route.",
    feat5_card_t: "Share with Friends",
    feat5_card_d: "Build a route, share the link, friends follow the same.",
    feat6_card_t: "Bengali Voice Guide",
    feat6_card_d: "Turn-by-turn Bengali instructions. Hands-free.",

    // Section 3: How it works
    hiw_sec_title: "How to use?",
    hiw_sec_sub: "Start in just 4 easy steps",
    hiw1_n: "01",
    hiw1_t: "Turn on Location",
    hiw1_d: "Browser will detect your live location.",
    hiw2_n: "02",
    hiw2_t: "Select Time",
    hiw2_d: "Pick 2/4/6 hours, or tap Top 5 / Top 10.",
    hiw3_n: "03",
    hiw3_t: "Start the Tour",
    hiw3_d: "One tap builds the route, then start walking.",
    hiw4_n: "04",
    hiw4_t: "Follow the Route",
    hiw4_d: "Follow the blue line and Bengali voice guide.",
    hiw_cta_btn: "Start Now",

    // Section 3.5: Why Cholo Pujo
    why_sec_title: "Why Cholo Pujo?",
    why_sec_sub: "Puja hopping is now easier and more enjoyable",
    why1_t: "Save Time",
    why1_d: "Less traffic, see more pandals.",
    why2_t: "Free for All",
    why2_d: "No login needed, zero advertisements.",
    why3_t: "Any Smartphone",
    why3_d: "No app download required.",
    why4_t: "Our City, Our Puja",
    why4_d: "Starting with Bardhaman & Katwa, more cities coming.",

    // Section 4: Cities covered
    city_sec_title: "Cities Covered",
    city_sec_sub: "More cities coming soon",
    city1_name: "Bardhaman",
    city1_count: "17 Pandals",
    city1_status: "Available",
    city2_name: "Katwa",
    city2_count: "6 Pandals",
    city2_status: "Available",
    city3_name: "Kolkata",
    city3_count: "Coming Soon",
    city3_status: "coming soon",

    // Section 5: Local businesses
    biz_sec_title: "Local Businesses",
    biz_sec_sub: "Featured shops and eateries nearby",
    biz_sponsored: "(Sponsored)",
    biz_empty: "Want to feature your business? Contact: +91 62951 11477, +91 99079 62182",
    biz_show_more: "Show more",
    biz_show_less: "Show less",
    biz_loading: "Loading...",

    // Section 6: Support project
    supp_sec_title: "Support the Project",
    supp_sec_sub: "This project is 100% free",
    supp_body: "We take no ads or subscriptions. If this initiative helps your Puja tour, you can make a small contribution to support server costs and expansion to more cities.",
    supp_qr_scan: "Scan with any UPI App",
    supp_qr_note: "Any amount, ₹10, ₹50, ₹100",
    supp_qr_soon: "QR Code Coming Soon",
    supp_amt_label: "Select Amount",
    supp_custom_amt: "Custom Amount",
    supp_amt_placeholder: "Enter amount",
    supp_pay_button: "Pay ₹{amt} via UPI",
    supp_scan_pay: "Scan to Pay ₹{amt}",
    supp_upi_note: "Works with Google Pay, PhonePe, Paytm & more",

    // Section 7: Emergency numbers
    emerg_sec_title: "Emergency Numbers",
    emerg_sec_sub: "For emergencies during Puja",
    emerg1_name: "Police Control Room",
    emerg1_num: "100",
    emerg2_name: "Hospital",
    emerg2_num: "108",
    emerg3_name: "Ambulance",
    emerg3_num: "102",
    emerg4_name: "Fire Brigade",
    emerg4_num: "101",

    // Section 8: Footer
    foot_tagline: "Less time, automatic routes",
    foot_init: "An initiative of",
    foot_nav_title: "Navigate",
    foot_home: "Home",
    foot_start: "Start Parikrama",
    foot_hiw: "How it works",
    foot_list: "Pandal List",
    foot_cities_title: "Cities",
    foot_bwn: "Bardhaman",
    foot_ktw: "Katwa",
    foot_more: "More Cities (Soon)",
    foot_contact_title: "Contact",
    foot_whatsapp: "Chat on WhatsApp",
    foot_email: "Contact: contact@devsaha.tech",
    foot_feedback: "Give Feedback",
    foot_github: "GitHub",
    foot_copy: "© 2026 DevSaha Tech · All rights reserved",
    foot_terms: "By using this site, you agree to our terms and conditions.",
    stat_verified: "Verified Pandals",
    stat_lag: "Server Lag",
    stat_free: "Free & Open Source",
    stat_lang: "English",
    stat_turn: "Turn Guidance",
    
    // Features
    feat_title: "What We Offer",
    feat_desc: "Join the festival without any hurdles. Our features make your pandal hopping easier.",
    feat1_t: "Shortest Round-Trip (2-Opt TSP)",
    feat1_d: "Start from anywhere, visit all pandals, and return in the shortest possible time.",
    feat2_t: "Time Budget Planner",
    feat2_d: "Select how many hours you have; the system automatically picks the best pandals and plans the route.",
    feat3_t: "Voice Navigation",
    feat3_d: "No need to look at your phone constantly. Audio guidance at every turn will tell you where to go.",
    feat4_t: "Police No-Entry & Traffic Filters",
    feat4_d: "Avoid temporary barricades and one-ways set up by Bardhaman Traffic Police with safe walking routes.",
    culture_title: "Heritage & Culture of Bardhaman",
    culture_desc1: "The centuries-old Sarbamangala Bari, historic Curzon Gate, 108 Shiva Temples, and the vibrant Barowari Durga Pujas of Badamtala and Alamganj, all part of our parikrama.",
    culture_desc2: "May our ancient city be adorned by the arrival of Goddess Durga.",
    

    // Footer
    foot_greeting: "Warmest greetings and best wishes for Sharadiya.",
    foot_desc: "A completely free and open-source project built for the festival-loving people of Bardhaman. Let's all enjoy a beautiful, organized, and traffic-free Puja.",
    foot_emergency: "Emergency Helpline",
    foot_police: "Bardhaman Police Control",
    foot_hospital: "Bardhaman Medical College Hospital",
    
    // Feedback
    feedback_button_aria: "Send feedback",
    feedback_title: "Send Feedback",
    feedback_category_label: "Category",
    feedback_category_general: "General",
    feedback_category_bug: "Bug / Problem",
    feedback_category_suggestion: "Suggestion",
    feedback_category_add_pandal: "Add a Pandal",
    feedback_category_data: "Data Correction",
    feedback_category_other: "Other",
    feedback_pandal_name_label: "Pandal name",
    feedback_message_label: "Your message",
    feedback_message_placeholder: "Type here...",
    feedback_submit: "Submit",
    feedback_cancel: "Cancel",
    feedback_thanks: "Thanks! We received your feedback.",
    feedback_error: "Sorry, submission failed. Please try again.",
    
    // Planner Phase 9B
    pl_time_label: "How much time?",
    pl_time_2h: "2 hours",
    pl_time_4h: "4 hours",
    pl_time_6h: "6 hours",
    pl_time_allday: "All day",
    pl_time_other: "Custom Time (minutes)",
    pl_other_time_title: "Custom Time (minutes)",
    pl_other_time_placeholder: "Enter a value between 30 and 720",
    pl_other_time_confirm: "OK",
    pl_other_time_cancel: "Cancel",
    pl_other_time_error_title: "Invalid Time",
    pl_other_time_error_body: "Please enter a number between 30 and 720 minutes.",
    pl_more_options: "More options",
    pl_start_tour: "Start Tour",
    pl_open_gmaps: "Open in Google Maps",
    pl_share: "Share",
    pl_select_from_map: "Pick from map",
    pl_selected_count: "{n} pandals selected",
    pl_confirm: "Confirm",
    pl_cancel: "Cancel",
    pl_open_first_10: "Start with first 10",
    pl_one_by_one: "One by one",
    pl_more_than_10: "Google Maps allows max 10 stops at once.",
    pl_continue_batch: "First 10 done? Tap for next {n}",
    share_title: "My Cholo Pujo route",
    share_text: "Cholo Pujo! {n} pandals",
    share_copied: "Link copied",
    search_pandals: "Search pandals...",
    batch_progress: "Batch {n} of {total}",
    batch_continue: "Tap for next batch",
    batch_done_toast: "All pandals visited!",
    site_visitors: "Total Website Visitors",

    pl_map_loading: "Loading map...",
    pl_top_n_all: "All",
    pl_load_error: "Could not load. Please try again.",
    pl_start_location: "Starting point",
    pl_other_time_title: "How many minutes?",
    pl_other_time_placeholder: "30 to 720 minutes",
    pl_other_time_confirm: "OK",
    pl_other_time_cancel: "Cancel",
    pl_all_pandals_visited: "All pandals visited!",
    pl_hope_enjoyed: "Hope you enjoyed it.",
    pl_from_your_location: "From your location",
    pl_tap_to_view_list: "Tap to view list",
    pl_clear_all: "Clear all",
    pl_batch_first_done: "Done with first {n}? Tap for next batch",
    pl_batch_almost: "Almost done, {n} stops left",
    pl_batch_counter: "Batch {current} of {total}",
    pl_time_pick_hint: "Pick a time, we'll build the best route",
    pl_device_error_title: "Unsupported device",
    pl_device_error_text: "Your device does not support location services.",
    map_no_location: "Live location not available. Please turn on GPS.",
    map_too_far: "You are far from the pandal ({dist} meters). Get within 120 meters to check-in.",
    map_already_checked_in: "You already checked in here! Try again after 2 hours.",
    map_checkin_success: "Check-in successful!",
    map_checkin_error: "Check-in failed.",
    map_osrm_fallback: "OSRM limit reached, showing direct route",
    map_visitors_present: "visitors present",
    map_take_me_here: "Take me here",
    map_remove_from_route: "- Remove from list",
    map_add_to_route: "+ Add to route",
    map_checkin_near: "Get closer to check in",
    map_checkin: "Check-in",
    map_give_tips: "Give tips",
    hud_tour_complete_voice: "You've returned to your starting point. Thank you for using Cholo Pujo!",
    hud_arrival_voice: "You have arrived at {name}. Enjoy the Puja!",
    hud_tour_complete_title: "You've returned to your starting point!",
    hud_tour_complete_sub: "Thank you for using Cholo Pujo!",
    hud_open_gmaps: "Open in Google Maps",
    hud_generic_pandal: "Pandal",
    hud_turn_distance: "In {dist} meters, {instruction}",
    hud_next_pandal: "Next pandal {name}, {dist} meters ahead",
    feedback_pandal_placeholder: "e.g. Sarbamangala",
    review_submitting: "Submitting...",
    gps_required_title: 'Turn on GPS',
    gps_required_body: 'This feature needs location permission for this site.',
    gps_required_ok: 'OK',
    gps_required_cancel: 'Cancel',
    gps_blocked_title: 'Location is blocked',
    gps_blocked_body: 'This site\'s location access is blocked in your browser. Open settings, set <b>Location → Allow</b>, and try again.',
  },
  bng: {
    // Navbar
    brand_title: "Puja Parikrama",
    brand_subtitle: "Bardhaman Edition",
    how_it_works: "Kibhabe Kaj Kore",
    pandal_list: "Pandal List",
    route_planner: "Route Planner",
    live_map: "Live Map",
    start_tour: "Parikrama Suru Korun",
    
    // HUD / Voice
    arrive: "Apni {name}-e pouchhe gechen. Ekhon thakur upobhog korun!",
    turn_left: "Left-e turn nin",
    turn_right: "Right-e turn nin",
    straight: "Soja jaan",
    uturn: "U-Turn nin",
    meters_after: "meter por",
    skip: "Next Pandal",
    end: "Sesh korun",
    tour_complete: "Parikrama Sesh",
    distance: "Durrotto",
    stop: "Stop",
    yes_reached: "Haa, pouche gechi",
    not_yet: "Na, pouchaini",
    next_pandal: "Next Pandal ➔",
    checkin_complete: "Dorshon Somponno",
    route_builder: "Route Builder",
    select_pandals: "Map theke pandal bechhe nin.",
    enable_mode: "Enable Mode",
    exit_mode: "Exit Mode",
    quick_stats: "Quick Stats",
    total_pandals: "Total Pandals",
    high_crowd: "High Crowd",
    add_to_route: "+ Route-e Add korun",
    added: "✔ Add kora hoyeche",
    transport_mode: "Jatayater Madhyom",
    
    // Hero Landing
    hero_pill: "Bardhaman • Katwa • 2026",
    hero_title: "Cholo, pujo dekhte jai",
    hero_title_p1: "Cholo,",
    hero_title_p2: "pujo dekhte jai",
    hero_motto: "Jekhan theke shuru, sekhanei shesh. Sera mondop gulo kom somoye",
    hero_one_line: "Sobcheye kom shomoye, kom jam-e, shera pandal gulo ghure dekhun. Free, login charai.",
    hero_btn_start: "Parikrama Shuru Korun",
    hero_btn_hiw: "Kivabe kaj kore",
    hero_subline: "23-ti pandal · Bardhaman o Katwa · Bangla-y Voice Guide",
    hero_stat_pandals: "23-ti Pandal",
    hero_stat_cities: "Bardhaman o Katwa",
    hero_stat_voice: "Bangla-y Voice Guide",
    hero_intro_text: "Bardhaman o Katwar sera Durga Puja mondop gulo sobcheye kom somoye ghure dekhun. Amader route planner nijei sobcheye kom durutte route toiri kore, ar Bangla voice guide diye hãtar poth dekhay. Free, login charai.",

    // Section 2: Features
    feat_sec_title: "Shudhu route planner noy",
    feat_sec_sub: "Pujo parikramar sob tool",
    feat1_card_t: "Sera mondop ek tap-e",
    feat1_card_d: "Top 5, Top 10 ba Top 15 — system nijei sera route banay.",
    feat2_card_t: "Somoy onujayi route",
    feat2_card_d: "2 ghonta theke sara din — jotota somoy ache, tototai mondop.",
    feat3_card_t: "Jekono mondop khujun",
    feat3_card_d: "Search kore sorasori Google Maps-e navigate korun.",
    feat4_card_t: "Nijer route banan",
    feat4_card_d: "Map theke pochhonder mondop bachun, system route sajiye debe.",
    feat5_card_t: "Bondhuder sathe share",
    feat5_card_d: "Route baniye link share korun, bondhurao eki route pabe.",
    feat6_card_t: "Bangla-y Voice Guide",
    feat6_card_d: "More more Bangla-y nirdeshona, phone-e takate hobe na.",

    // Section 3: How it works
    hiw_sec_title: "Kivabe byabahar korben?",
    hiw_sec_sub: "Matro 4-ti sohoj dhape shuru",
    hiw1_n: "01",
    hiw1_t: "Location chalu korun",
    hiw1_d: "Browser tomar location shonakhto korbe.",
    hiw2_n: "02",
    hiw2_t: "Shomoy beche nin",
    hiw2_d: "2/4/6 ghonta beche nin, ba Top 5 / Top 10 tap korun.",
    hiw3_n: "03",
    hiw3_t: "Parikrama shuru korun",
    hiw3_d: "Ek tape route toiri hobe, tarpor hãtতে shuru korun.",
    hiw4_n: "04",
    hiw4_t: "Route onushoron korun",
    hiw4_d: "Nil route o Bangla voice guide onushoron korun.",
    hiw_cta_btn: "Ekhoni shuru korun",

    // Section 4: Cities covered
    city_sec_title: "Jesob shohore ache",
    city_sec_sub: "Aro shohor jog hocche shighroi",
    city1_name: "Bardhaman",
    city1_count: "17-ti Pandal",
    city1_status: "Available",
    city2_name: "Katwa",
    city2_count: "6-ti Pandal",
    city2_status: "Available",
    city3_name: "Kolkata",
    city3_count: "Shighroi asche",
    city3_status: "coming soon",

    // Section 5: Local businesses
    biz_sec_title: "Sthaniyo Byabasa",
    biz_sec_sub: "Kacher dokan o khabarer jayga",
    biz_sponsored: "(Sponsored)",
    biz_empty: "Tomar byabasa ekhane dekhate chan? Jogajog korun: +91 62951 11477, +91 99079 62182",
    biz_show_more: "Aro dekhan",
    biz_show_less: "Kom dekhan",
    biz_loading: "Load hochhe...",

    // Section 6: Support project
    supp_sec_title: "Somorthon janan",
    supp_sec_sub: "Ei project-ti shompurno free",
    supp_body: "Amra kono biggapon ba subscription nei na. Jodi ei initiative tomar pujo parikramay shahajjo kore, tumi chaile shamanyo obodan rakhte paro.",
    supp_qr_scan: "UPI diye scan korun",
    supp_qr_note: "Jekono poriman, ₹10, ₹50, ₹100",
    supp_qr_soon: "QR Code Shighroi Asche",
    supp_amt_label: "Poriman bachun",
    supp_custom_amt: "Nijer icchemoto poriman",
    supp_amt_placeholder: "Poriman likhun",
    supp_pay_button: "UPI diye ₹{amt} pathan",
    supp_scan_pay: "₹{amt} pathate scan korun",
    supp_upi_note: "Google Pay, PhonePe, Paytm shoho shob UPI app-e kaj kore",

    // Section 7: Emergency numbers
    emerg_sec_title: "Joruri Number",
    emerg_sec_sub: "Pujor shomoy proyojon hole",
    emerg1_name: "Bardhaman Police Control",
    emerg1_num: "100",
    emerg2_name: "Bardhaman Medical College",
    emerg2_num: "108",
    emerg3_name: "Ambulance",
    emerg3_num: "102",
    emerg4_name: "Fire Station",
    emerg4_num: "101",

    // Section 8: Footer
    foot_tagline: "Kom shomoy, automatic route",
    foot_init: "Ekti uddyog",
    foot_nav_title: "Navigation",
    foot_home: "Home",
    foot_start: "Parikrama Shuru Korun",
    foot_hiw: "Kivabe kaj kore",
    foot_list: "Pandal List",
    foot_cities_title: "Shohorshomuho",
    foot_bwn: "Bardhaman",
    foot_ktw: "Katwa",
    foot_more: "Aro Shohor (Shighroi)",
    foot_contact_title: "Jogajog",
    foot_whatsapp: "WhatsApp-e jogajog",
    foot_email: "Jogajog: contact@devsaha.tech",
    foot_feedback: "Motamot janan",
    foot_github: "GitHub",
    foot_copy: "© 2026 DevSaha Tech · Sob odhikar shongrokhito",
    foot_terms: "Ei site-ti byabahar kore apni amader shortaboli mene nicchen.",
    stat_verified: "Verified Pandal",
    stat_lag: "Server Lag",
    stat_free: "Free",
    stat_lang: "Banglish",
    stat_turn: "Turn Guidance",
    
    // Features
    feat_title: "Amra Ki Ki Dichhi",
    feat_desc: "Utsobe jog din kono badha charai. Amader feature-gulo apnar parikrama ke korbe aro sohoj.",
    feat1_t: "Shortest Round-Trip (2-Opt TSP)",
    feat1_d: "Jekhan theke pujo dekhte beroben, sob thakur dekhe sobcheye kom somoye sekhanei phire asben.",
    feat2_t: "Time Budget Planner",
    feat2_d: "Apnar hate thik koto ghonta somoy ache select korun; system nije theke sera pandal-gulo beche route sajiye debe.",
    feat3_t: "Voice Navigation",
    feat3_d: "Rastay hatar somoy phone-e barbar takate hobe na, more more audio guidance janiye debe kon dike jaben.",
    feat4_t: "Police No-Entry & Traffic Filter",
    feat4_d: "Bardhaman traffic police-er samoyik barricade o one-way eriye shudhu hatar nirapod route.",
    culture_title: "Bardhaman-er Aitihyo O Sonskriti",
    culture_desc1: "Shotabdi prachin Sarbamangala Bari, aitihasik Curzon Gate, 108 Shiva Temple, ar Badamtala o Alamganj-er bornaddho Barowari Durga Pujar oporup soundorjyo, sob miliye amader ei parikrama.",
    culture_desc2: "Ma Durgar agomone seje uthuk amader ei prachin sohor.",
    

    // Footer
    foot_greeting: "Shubho Sharodiyar priti, shubhechha o antorik abhinondon.",
    foot_desc: "Bardhaman-er utsob-premi manusder jonno toiri ekti sompurno free o open-source project. Ashun sobai mile ek sundor, sushrinkhol o jam-mukt pujo upobhog kori.",
    foot_emergency: "Emergency Helpline",
    foot_police: "Police Control",
    foot_hospital: "Hospital",
    
    // Planner Phase 9B
    pl_time_label: "Koto somoy ache?",
    pl_time_2h: "2 ghonta",
    pl_time_4h: "4 ghonta",
    pl_time_6h: "6 ghonta",
    pl_time_allday: "Sara din",
    pl_time_other: "Onnanno",
    pl_more_options: "Aro bikolpo",
    pl_start_tour: "Parikrama suru korun",
    pl_open_gmaps: "Google Maps-e khulun",
    pl_share: "Share",
    pl_select_from_map: "Map theke bachun",
    pl_selected_count: "{n}ti mondop bechhechen",
    pl_confirm: "Sompurno korun",
    pl_cancel: "Batil",
    pl_open_first_10: "Prothom 10 diye suru korun",
    pl_one_by_one: "Ekta ekta kore jaan",
    pl_more_than_10: "10 tir beshi mondop Google Maps-e ekshathe dekhano jabe na.",
    pl_continue_batch: "Prothom 10 shesh? Porer {n}tir jonno click korun",
    share_title: "Amar pujo parikramar route",
    share_text: "Cholo pujo dekhte jai! {n}ti mondop",
    share_copied: "Link copy hoyeche",
    search_pandals: "Mondop khujun...",
    batch_progress: "Batch {n} / {total}",
    batch_continue: "Porer tir jonno click korun",
    batch_done_toast: "Sob mondop dekha shesh!",
    site_visitors: "Mot website darshonarthi",

    why_sec_title: "Kano Cholo Pujo?",
    why_sec_sub: "Pujo parikrama ebar aro sohoj, aro anondomoy",
    why1_t: "Somoy bachan",
    why1_d: "Kom jam-e, beshi pandal dekhun.",
    why2_t: "Sobar jonno free",
    why2_d: "Kono login nei, kono biggapon nei.",
    why3_t: "Jekono phone-e",
    why3_d: "App download korar dorkar nei.",
    why4_t: "Nijer shohor, nijer pujo",
    why4_d: "Bardhaman o Katwa theke shuru, aro shohor asche.",
    feedback_button_aria: "Motamot janan",
    feedback_title: "Apnar motamot janan",
    feedback_category_label: "Bibhag",
    feedback_category_general: "Sadharon motamot",
    feedback_category_bug: "Somosya / Bug",
    feedback_category_suggestion: "Poribortoner prostab",
    feedback_category_add_pandal: "Notun mondop jog korun",
    feedback_category_data: "Tothyo songsodhon",
    feedback_category_other: "Onyanyo",
    feedback_pandal_name_label: "Mondoper nam",
    feedback_message_label: "Apnar motamot",
    feedback_message_placeholder: "Ekhane likhun...",
    feedback_submit: "Pathan",
    feedback_cancel: "Batil",
    feedback_thanks: "Dhonnobad! Apnar motamot amra peyechi.",
    feedback_error: "Dukkhito, pathano jayni. Abar chesta korun.",

    pl_map_loading: "Map load hochhe...",
    pl_top_n_all: "Sob",
    pl_load_error: "Load korte problem hoyeche, abar chesta korun.",
    pl_start_location: "Shurur sthan",
    pl_other_time_title: "Koto minute somoy ache?",
    pl_other_time_placeholder: "30 theke 720 minute",
    pl_other_time_confirm: "Thik ache",
    pl_other_time_cancel: "Batil",
    pl_all_pandals_visited: "Sob mondop dekha shesh!",
    pl_hope_enjoyed: "Asha kori bhalo legeche.",
    pl_from_your_location: "Apnar obosthan theke",
    pl_tap_to_view_list: "List dekhte tap korun",
    pl_clear_all: "Sob muchun",
    pl_batch_first_done: "Prothom {n}ti shesh? Porertir jonno click korun",
    pl_batch_almost: "Pray shesh, baki {n}ti mondop",
    pl_batch_counter: "Batch {current} / {total}",
    pl_time_pick_hint: "Somoy bechhe nin, amra sera route baniye deb",
    pl_device_error_title: "Oshomorthito device",
    pl_device_error_text: "Apnar device-e location service support korche na.",
    map_no_location: "Apnar live location paoa jacche na. Doya kore GPS on korun.",
    map_too_far: "Apni mondop theke onek dure achen ({dist} meter). 120 meter-er modhye ele check-in korte parben.",
    map_already_checked_in: "Apni itimodhye ei mondope check-in korechen! 2 ghonta por abar chesta korun.",
    map_checkin_success: "Check-in sothik bhabe somponno hoyeche!",
    map_checkin_error: "Check-in korte somosya hoyeche.",
    map_osrm_fallback: "OSRM limit pouchheche, direct route dekhano hocche",
    map_visitors_present: "jon darshonarthi uposthito",
    map_take_me_here: "Ekhane jaan",
    map_remove_from_route: "- List theke bad din",
    map_add_to_route: "+ Route-e jog korun",
    map_checkin_near: "Kache gele check-in korte parben",
    map_checkin: "Check-in",
    map_give_tips: "Tips din",
    hud_tour_complete_voice: "Apni shurur sthane pouchhe gechen. Cholo Pujo byabohar korar jonno dhonnobad!",
    hud_arrival_voice: "{name}-e pouchhe gechen. Ekhon thakur upobhog korun!",
    hud_tour_complete_title: "Shurur sthane pouchhechen!",
    hud_tour_complete_sub: "Cholo Pujo byabohar korar jonno dhonnobad!",
    hud_open_gmaps: "Google Maps-e cholun",
    hud_generic_pandal: "Mondop",
    hud_turn_distance: "{dist} meter por {instruction}",
    hud_next_pandal: "Poroborti mondop {name}, ar {dist} meter",
    feedback_pandal_placeholder: "Jemon: Sorbomongola",
    review_submitting: "Submit hochhe...",
    gps_required_title: 'GPS Chalu Korun',
    gps_required_body: 'Ei feature use korte site-er location permission dite hobe.',
    gps_required_ok: 'Thik Ache',
    gps_required_cancel: 'Cancel',
    gps_blocked_title: 'Location Block Kora Ache',
    gps_blocked_body: 'Apnar browser-e ei site-er location block kora ache. Settings theke <b>Location → Allow</b> kore abar chesta korun.',
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState('bn');

  useEffect(() => {
    const saved = localStorage.getItem('puja_lang');
    if (saved && ['bn', 'en', 'bng'].includes(saved)) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang) => {
    setLangState(newLang);
    localStorage.setItem('puja_lang', newLang);
  };

  // Translation helper
  const t = (key, params = {}) => {
    let str = translations[lang]?.[key] || translations['en']?.[key] || key;
    
    // Replace params (e.g. {name})
    Object.keys(params).forEach(p => {
      str = str.replace(`{${p}}`, params[p]);
    });
    
    return str;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
